<?php
include('./PDO/Connection.php');

$model = isset($_GET['model'])?$_GET['model']:'';
// 28欄
$sql = "SELECT ID,STUDENT_ID,MODEL,PRICE,UNLOCK_STATUS,FILE_NAME,IMG_PATH,NAME,ADDRESS,PHONE,EMAIL,PORFOLIO,AUTOBIOGRAPHY,
WORK_EXPERIENCE_JOB,DURING_WORK,WORK_CONTENT,SCHOOL,DURING_SCHOOL,DEPARTMENT,ATTEND_SCHOOL_STATUS,SCHOOL_EXPERIENCE,JOB_APPLY,
SKILL1,SKILL2,SKILL3,SKILL4,LANGUAGE1,LANGUAGE2 FROM RESUME WHERE MODEL = ?";
$statement = $pdo->prepare($sql);
$statement->bindValue(1,$model);
$statement->execute();
echo json_encode($statement->fetchAll());

?>